SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, PFUNC.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFILIAL), 'N/A')
  ,FKCODSECAO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSECAO), 'N/A')
  ,FKCODFUNCAO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODFUNCAO), 'N/A')
  ,FKCODSINDICATO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CODSINDICATO), 'N/A')
  ,FKCODSITUACAO = UPPER(ISNULL(CONVERT(VARCHAR(50), PFUNC.CODSITUACAO), 'N/A'))
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PSECAO.CODFILIAL) + '_' + CONVERT(VARCHAR, PSECAO.CODDEPTO), 'N/A')
  ,FKCODCUSTO = ISNULL(CONVERT(VARCHAR, PFUNC.CODCOLIGADA), 'N/A') + '_' + ISNULL(CONVERT(VARCHAR(50), PSECAO.NROCENCUSTOCONT), 'N/A')
  ,FKPESSOA = UPPER(CONVERT(VARCHAR(50), PFUNC.CODPESSOA))
  ,PKCHAPA = CONVERT(VARCHAR, PFUNC.CODCOLIGADA) + '_' + UPPER(CONVERT(VARCHAR(25), PFUNC.CHAPA))
  ,[Chapa do Funcionario] = UPPER(CONVERT(VARCHAR(25), PFUNC.CHAPA))
  ,[Nome do Funcionario] = UPPER(CONVERT(VARCHAR(255), PFUNC.NOME))
  ,[CPF do Funcionario] = UPPER(CONVERT(VARCHAR(255), PPESSOA.CPF))
  ,[Sexo do Funcionario] = UPPER(CONVERT(VARCHAR(255), PPESSOA.SEXO))
  ,[Grau de Instrucao] = UPPER(ISNULL(CONVERT(VARCHAR(255), PCODINSTRUCAO.DESCRICAO), 'N/A'))
  ,[Jornada do Funcionario] = ISNULL(PFUNC.JORNADA, 0.00)
  ,[Jornada Mensal do Funcionario] = ISNULL(PFUNC.JORNADAMENSAL / 60.00, 0.00)
  ,[Codigo do Tipo] = UPPER(ISNULL(CONVERT(VARCHAR(50), PFUNC.CODTIPO), 'N/A'))
  ,[Descricao do Tipo] = UPPER(ISNULL(CONVERT(VARCHAR(255), PTPFUNC.DESCRICAO), 'N/A'))
  ,[Codigo do Horario] = UPPER(ISNULL(CONVERT(VARCHAR(50), PFUNC.CODHORARIO), 'N/A'))
  ,[Descricao do Horario] = UPPER(ISNULL(CONVERT(VARCHAR(255), AHORARIO.DESCRICAO), 'N/A'))
  ,[Estado Civil do Funcionario] = UPPER(ISNULL(CONVERT(VARCHAR(255), PPESSOA.ESTADOCIVIL), 'N/A'))
  ,[Nacionalidade do Funcionario] = UPPER(ISNULL(CONVERT(VARCHAR(255), PPESSOA.NACIONALIDADE), 'N/A'))
  ,[Cor Raca do Funcionario] = UPPER(ISNULL(CONVERT(VARCHAR(255), PCORRACA.DESCRICAO), 'N/A'))
  ,[Data de Nascimento] = CONVERT(VARCHAR(10), PPESSOA.DTNASCIMENTO, 112)
  ,[Geracao do Funcionario] = CASE
     WHEN PPESSOA.DTNASCIMENTO = NULL THEN 'N/A'
     WHEN DATEPART(YEAR, PPESSOA.DTNASCIMENTO) <= 1964 THEN 'BABY BOOMER'
     WHEN DATEPART(YEAR, PPESSOA.DTNASCIMENTO) BETWEEN 1965 AND 1980 THEN 'X'
     WHEN DATEPART(YEAR, PPESSOA.DTNASCIMENTO) BETWEEN 1981 AND 1996 THEN 'Y'
     WHEN DATEPART(YEAR, PPESSOA.DTNASCIMENTO) BETWEEN 1997 AND 2012 THEN 'Z'
     ELSE 'ALFA' END
  ,[Data de Admissao] = CONVERT(VARCHAR(10), PFUNC.DATAADMISSAO, 112)
  ,[Data de Demissao] = CONVERT(VARCHAR(10), PFUNC.DATADEMISSAO, 112)
  ,[Data de Transferencia] = CONVERT(VARCHAR(10), PFUNC.DTTRANSFERENCIA, 112)
  ,[Data de Alteracao RECNO] = ISNULL(CONVERT(VARCHAR(10), PFUNC.RECMODIFIEDON, 112), '19000101')
  ,[Codigo Tipo Admissao] = UPPER(ISNULL(CONVERT(VARCHAR(10), PFUNC.TIPOADMISSAO), 'N/A'))
  ,[Descricao Tipo Admissao] = UPPER(ISNULL(CONVERT(VARCHAR(255), PTPADMISSAO.DESCRICAO), 'N/A'))
  ,[Codigo Tipo Demissao] = UPPER(ISNULL(CONVERT(VARCHAR(10), PFUNC.TIPODEMISSAO), 'N/A'))
  ,[Descricao Tipo Demissao] = UPPER(ISNULL(CONVERT(VARCHAR(255), PTPDEMISSAO.DESCRICAO), 'N/A'))
  ,[Codigo Motivo Admissao] = UPPER(ISNULL(CONVERT(VARCHAR(10), PFUNC.MOTIVOADMISSAO), 'N/A'))
  ,[Descricao Motivo Admissao] = UPPER(ISNULL(CONVERT(VARCHAR(255), PMOTADMISSAO.DESCRICAO), 'N/A'))
  ,[Codigo Motivo Demissao] = UPPER(ISNULL(CONVERT(VARCHAR(10), PFUNC.MOTIVODEMISSAO), 'N/A'))
  ,[Descricao Motivo Demissao] = UPPER(ISNULL(CONVERT(VARCHAR(255), PMOTDEMISSAO.DESCRICAO), 'N/A'))
  ,[MSA] = CASE WHEN MSA.MSA IS NULL THEN CONVERT(VARCHAR(10), GETDATE(), 112) ELSE CONVERT(VARCHAR(10), MSA.MSA, 112) END
  ,[MSP] = CASE WHEN MSP.MSP IS NULL THEN CONVERT(VARCHAR(10), GETDATE(), 112) ELSE CONVERT(VARCHAR(10), MSP.MSP, 112) END
  ,[Tempo de Casa] = CASE
     WHEN DATEDIFF(DAY, PFUNC.DATAADMISSAO, GETDATE()) <= 179 THEN '1'
     WHEN DATEDIFF(DAY, PFUNC.DATAADMISSAO, GETDATE()) <= 364 THEN '2'
     WHEN DATEDIFF(DAY, PFUNC.DATAADMISSAO, GETDATE()) <= 1094 THEN '3'
     WHEN DATEDIFF(DAY, PFUNC.DATAADMISSAO, GETDATE()) <= 1824 THEN '4'
     WHEN DATEDIFF(DAY, PFUNC.DATAADMISSAO, GETDATE()) <= 2554 THEN '5'
     WHEN DATEDIFF(DAY, PFUNC.DATAADMISSAO, GETDATE()) <= 3284 THEN '6'
     WHEN DATEDIFF(DAY, PFUNC.DATAADMISSAO, GETDATE()) > 3284 THEN '7'
     ELSE 'N/A' END
  ,[Tempo de Ultima Acao Salarial] = CASE
     WHEN DATEDIFF(DAY, MSA.MSA, GETDATE()) <= 179 THEN '1'
     WHEN DATEDIFF(DAY, MSA.MSA, GETDATE()) <= 364 THEN '2'
     WHEN DATEDIFF(DAY, MSA.MSA, GETDATE()) <= 1094 THEN '3'
     WHEN DATEDIFF(DAY, MSA.MSA, GETDATE()) <= 1824 THEN '4'
     WHEN DATEDIFF(DAY, MSA.MSA, GETDATE()) <= 2554 THEN '5'
     WHEN DATEDIFF(DAY, MSA.MSA, GETDATE()) <= 3284 THEN '6'
     WHEN DATEDIFF(DAY, MSA.MSA, GETDATE()) > 3284 THEN '7'
     ELSE 'N/A' END
  , [Codigo Equipe] = CONVERT(VARCHAR,PEQUIPE.CODCLIENTE)
  , [Descricao Equipe] = CONVERT(VARCHAR,PEQUIPE.DESCRICAO)

  ,[Email] = UPPER(CONVERT(VARCHAR(255), PPESSOA.EMAIL))
  ,[Rua do Funcionario] = UPPER(CONVERT(VARCHAR(255), PPESSOA.RUA))
  ,[Numero da casa] = UPPER(CONVERT(VARCHAR(255), PPESSOA.NUMERO))
  ,[Bairro do Funcionario] = UPPER(CONVERT(VARCHAR(255), PPESSOA.BAIRRO))
  ,[Cidade do Funcionario] = UPPER(CONVERT(VARCHAR(255), PPESSOA.CIDADE))
  ,[Estado Natal do Funcionario] = UPPER(CONVERT(VARCHAR(255), PPESSOA.ESTADONATAL))
  ,[Endereco] = UPPER(CONVERT(VARCHAR(255), PPESSOA.EMAIL))
  ,[Carteira de Identidade] = UPPER(CONVERT(VARCHAR(255), PPESSOA.CARTIDENTIDADE))
  ,[CEP do Funcionario]  = UPPER(CONVERT(VARCHAR(255), PPESSOA.CEP))
  ,[PIS Funcionario] = UPPER(CONVERT(VARCHAR(255), PFUNC.PISPASEP))
  ,[Telefone do Funcionario] = UPPER(CONVERT(VARCHAR(255), PPESSOA.TELEFONE1))
  
FROM
  PFUNC WITH (NOLOCK)
  INNER JOIN PPESSOA WITH (NOLOCK) ON
      PFUNC.CODPESSOA = PPESSOA.CODIGO
  INNER JOIN PSECAO WITH (NOLOCK) ON
      PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA
  AND PFUNC.CODSECAO = PSECAO.CODIGO
  LEFT JOIN PMOTADMISSAO WITH (NOLOCK) ON
      PFUNC.CODCOLIGADA = PMOTADMISSAO.CODCOLIGADA
  AND PFUNC.MOTIVOADMISSAO = PMOTADMISSAO.CODINTERNO
  LEFT JOIN PMOTDEMISSAO WITH (NOLOCK) ON
      PFUNC.CODCOLIGADA = PMOTDEMISSAO.CODCOLIGADA
  AND PFUNC.MOTIVODEMISSAO = PMOTDEMISSAO.CODINTERNO
  LEFT JOIN PTPADMISSAO WITH (NOLOCK) ON
  PFUNC.TIPOADMISSAO = PTPADMISSAO.CODINTERNO
  LEFT JOIN PTPDEMISSAO WITH (NOLOCK) ON
  PFUNC.TIPODEMISSAO = PTPDEMISSAO.CODINTERNO
  LEFT JOIN PTPFUNC WITH (NOLOCK) ON
  PFUNC.CODTIPO = PTPFUNC.CODINTERNO
  LEFT JOIN AHORARIO WITH (NOLOCK) ON
      PFUNC.CODCOLIGADA = AHORARIO.CODCOLIGADA
  AND PFUNC.CODHORARIO = AHORARIO.CODIGO
  LEFT JOIN PCODINSTRUCAO WITH (NOLOCK) ON
      PPESSOA.GRAUINSTRUCAO = PCODINSTRUCAO.CODINTERNO
  LEFT JOIN PCORRACA WITH (NOLOCK) ON
      PCORRACA.CODCLIENTE = PPESSOA.CORRACA
  LEFT JOIN (
    SELECT
       SAL.CODCOLIGADA
      ,SAL.CHAPA
      ,DTMUDANCA MSA
    FROM 
      PFHSTSAL SAL
    WHERE
          SAL.DTMUDANCA = (SELECT MAX(DTMUDANCA) FROM PFHSTSAL AUX WHERE SAL.CODCOLIGADA=AUX.CODCOLIGADA AND SAL.CHAPA=AUX.CHAPA)
      AND SAL.MOTIVO IN ('02','07','93','94','95')
  ) MSA ON
      PFUNC.CODCOLIGADA = MSA.CODCOLIGADA AND PFUNC.CHAPA = MSA.CHAPA
  LEFT JOIN (
    SELECT
       FCO.CODCOLIGADA
      ,FCO.CHAPA
      ,DTMUDANCA MSP
    FROM 
      PFHSTFCO FCO
    WHERE
          FCO.DTMUDANCA=(SELECT MAX(DTMUDANCA) FROM PFHSTFCO AUX WHERE FCO.CODCOLIGADA=AUX.CODCOLIGADA AND FCO.CHAPA=AUX.CHAPA)
      AND FCO.MOTIVO IN ('03','94')
  ) MSP ON
      PFUNC.CODCOLIGADA = MSP.CODCOLIGADA AND PFUNC.CHAPA = MSP.CHAPA
  LEFT JOIN PEQUIPE WITH (NOLOCK)
        ON PEQUIPE.CODCLIENTE = PFUNC.CODEQUIPE
   LEFT JOIN PCODSITUACAO 
  		ON PFUNC.CODSITUACAO = PCODSITUACAO.CODINTERNO

UNION ALL

SELECT
   INSTANCIA = <<INSTANCIA>>
  ,FKCODCOLIGADA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA)
  ,FKCODFILIAL = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODSECAO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODFUNCAO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODSINDICATO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKCODSITUACAO = 'N/A'
  ,FKCODDEPARTAMENTO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A_N/A'
  ,FKCODCUSTO = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,FKPESSOA = 'N/A'
  ,PKCHAPA = CONVERT(VARCHAR, GCOLIGADA.CODCOLIGADA) + '_N/A'
  ,[Chapa do Funcionario] = 'N/A'
  ,[Nome do Funcionario] = 'N/A'
  ,[CPF do Funcionario] = 'N/A'
  ,[Sexo do Funcionario] = 'N/A'
  ,[Grau de Instrucao] = 'N/A'
  ,[Jornada do Funcionario] = 0
  ,[Jornada Mensal do Funcionario] = 0
  ,[Codigo do Tipo] = 'N/A'
  ,[Descricao do Tipo] = 'N/A'
  ,[Codigo do Horario] = 'N/A'
  ,[Descricao do Horario] = 'N/A'
  ,[Estado Civil do Funcionario] = 'N/A'
  ,[Nacionalidade do Funcionario] = 'N/A'
  ,[Cor Raca do Funcionario] = 'N/A'
  ,[Data de Nascimento] = null
  ,[Geracao do Funcionario] = 'N/A'
  ,[Data de Admissao] = null
  ,[Data de Demissao] = null
  ,[Data de Transferencia] = null
  ,[Data de Alteracao RECNO] = null
  ,[Codigo Tipo Admissao] = 'N/A'
  ,[Desccricao Tipo Admissao] = 'N/A'
  ,[Codigo Tipo Demissao] = 'N/A'
  ,[Descricao Tipo Demissao] = 'N/A'
  ,[Codigo Motivo Admissao] = 'N/A'
  ,[Descricao Motivo Admissao] = 'N/A'
  ,[Codigo Motivo Demissao] = 'N/A'
  ,[Descricao Motivo Demissao] = 'N/A'
  ,[MSA] = null
  ,[MSP] = null
  ,[Tempo de Casa] = null
  ,[Tempo de Ultima Acao Salarial] = null
  ,[Codigo Equipe] = 'N/A'
  ,[Descricao Equipe] = 'N/A'
  
  ,[Email] = 'N/A'
  ,[Rua do Funcionario] = 'N/A'
  ,[Numero da casa] = 'N/A'
  ,[Bairro do Funcionario] = 'N/A'
  ,[Cidade do Funcionario] = 'N/A'
  ,[Estado Natal do Funcionario] = 'N/A'
  ,[Endereco] = 'N/A'
  ,[Carteira de Identidade] = 'N/A'
  ,[CEP do Funcionario]  = 'N/A'
  ,[PIS Funcionario] = 'N/A'
  ,[Telefone do Funcionario] = 'N/A'
FROM
  GCOLIGADA WITH (NOLOCK)
;