SELECT
    INSTANCIA = <<INSTANCIA>>
    ,FKCODCOLIGADA = CONVERT(VARCHAR, EVENTO.CODCOLIGADA),
    FKCHAPA = CONVERT(VARCHAR, EVENTO.CODCOLIGADA) + '_' + ISNULL(CONVERT(VARCHAR, PFUNC.CHAPA), 'N/A'),
    EVENTO.EXTRAEXECUTADO AS EXTRA_ATUAL,
    EVENTO.ATRASO AS ATRASO_ATUAL,
    EVENTO.BASE AS HORARIO_BASE,
    EVENTO.FALTA AS FALTA_ATUAL,
    CONVERT(VARCHAR(10), EVENTO.DATA, 112) AS DIA_DATA


FROM AAFHTFUN EVENTO WITH (NOLOCK)
    INNER JOIN PFUNC WITH (NOLOCK) ON
        PFUNC.CODCOLIGADA = EVENTO.CODCOLIGADA
        AND PFUNC.CHAPA = EVENTO.CHAPA
        