SELECT
  'P |01|01' 
      AS BK_EMPRESA
  , CASE
    WHEN SD2.D2_FILIAL IS NULL
    THEN 'P |01||'
    ELSE 'P |01|01'+ CAST( SD2.D2_FILIAL AS CHAR (4) )
    END
      AS BK_FILIAL
  , SF2.F2_SERIE  
      AS SERIE_DA_NOTA_FISCAL
  , SF2.F2_DOC
      AS NUMERO_DA_NOTA_FISCAL
  , SD2.D2_PEDIDO 
      AS NUMERO_PEDIDO_VENDA
  , SD2.D2_ITEM   
      AS NUMERO_ITEM
  , CASE
      WHEN LTRIM(RTRIM( SF2.F2_EMISSAO)) = ' '
      THEN ' '
      ELSE SF2.F2_EMISSAO
      END 
        AS DATA_DE_EMISSAO
  , CASE
      WHEN LTRIM(RTRIM( SF2.F2_EMINFE)) = ' '
      THEN ' '
      ELSE SF2.F2_EMINFE
      END
        AS DATA_SAIDA_NF
  , SF2.F2_TPFRETE
      AS TIPO_DE_FRETE
  , SD2.D2_TIPO
      AS TIPO_DE_NOTA_FISCAL
  , SD2.D2_ORIGLAN
      AS ORIGEM_DO_LANCAMENTO
  , 'P |01|SB1010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SB1.B1_FILIAL,' ') )+'|'+RTRIM( COALESCE( SD2.D2_COD,' ') ),' '),'|')
      AS BK_ITEM
  , 'P |01|SBM010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SBM.BM_FILIAL,' ') )+'|'+RTRIM( COALESCE( SB1.B1_GRUPO,' ') ),' '),'|')
      AS BK_GRUPO_ESTOQUE
  , 'P |01|SA3010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SA3.A3_FILIAL,' ') )+'|'+RTRIM( COALESCE( SF2.F2_VEND1,' ') ),' '),'|')
      AS BK_VENDEDOR
  , 'P |01|SF4010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SF4.F4_FILIAL,' ') )+'|'+RTRIM( COALESCE( SD2.D2_TES,' ') ),' '),'|')
      AS BK_TES
  , 'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM( COALESCE( CFOP.X5_FILIAL,' ') )+'|'+RTRIM( COALESCE( SD2.D2_CF,' ') ),' '),'|')
      AS BK_CFOP
  , 'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SA1.A1_FILIAL,' ') )+'|'+RTRIM( COALESCE( SA1.A1_TIPO,' ') ),' '),'|')
      AS BK_GRUPO_CLIENTE
  , 'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SA1.A1_FILIAL,' ') )+'|'+RTRIM( COALESCE( SD2.D2_CLIENTE,' ') )+RTRIM( COALESCE( SD2.D2_LOJA,' ') ),' '),'|') 
      AS BK_CLIENTE
  , CASE
      WHEN SA1.A1_COD_MUN = ' '
      THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SA1.A1_EST,' ') ),' '),'|')
      ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SA1.A1_EST,' ') )+RTRIM( COALESCE( SA1.A1_COD_MUN,' ') ),' '),'|')
      END
        AS BK_REGIAO
  ,'P |01|SE4010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SE4.E4_FILIAL,' ') )+'|'+RTRIM( COALESCE( SF2.F2_COND,' ') ),' '),'|')    
      AS BK_CONDICAO_DE_PAGAMENTO
  ,'P |01|ACY010|'+ COALESCE(NULLIF(RTRIM( COALESCE( ACY.ACY_FILIAL,' ') )+'|'+RTRIM( COALESCE( SA1.A1_GRPVEN,' ') ),' '),'|') 
      AS BK_REGIAO_COMERCIAL
  ,'P |01|SAH010|'+ COALESCE(NULLIF(RTRIM( COALESCE( SAH.AH_FILIAL,' ') )+'|'+RTRIM( COALESCE( SD2.D2_UM,' ') ),' '),'|')      
      AS BK_UNIDADE_DE_MEDIDA
  , CAST( COALESCE( SD2.D2_VALBRUT,0) AS DECIMAL(14,2))
      AS VL_FATURAMENTO_TOTAL
  , CAST( COALESCE( SD2.D2_VALICM,0) AS DECIMAL(14,2))
      AS VL_ICMS_FATURAMENTO
  , CAST( COALESCE( SD2.D2_VALIPI,0) AS DECIMAL(14,2))
      AS VL_IPI_FATURAMENTO
  , CAST( COALESCE( SD2.D2_VALFRE,0) AS DECIMAL(14,2))
      AS VL_FRETE_NF
  , CAST( COALESCE( SD2.D2_DESPESA,0) AS DECIMAL(14,2))
      AS VL_DESPESA
  , CAST( COALESCE( SD2.D2_TOTAL,0) AS DECIMAL(14,2))
      AS VL_FATURAMENTO_MERCADORIA
  , CAST( COALESCE( SD2.D2_VALIMP6,0) AS DECIMAL(14,2))
      AS VL_PIS_FATURAMENTO
  , CAST( COALESCE( SD2.D2_VALIMP5,0) AS DECIMAL(14,2))
      AS VL_COFINS_FATURAMENTO
  , CAST( COALESCE( SD2.D2_QUANT,0) AS DECIMAL(11,2))
      AS QTD_FATURADA_ITEM
  , CAST( COALESCE( SD2.D2_VALISS,0) AS DECIMAL(14,2))
      AS VL_ISS_FATURAMENTO
  , CAST( COALESCE( SD2.D2_ICMSRET,0) AS DECIMAL(14,2))
      AS VL_ICMS_SUBST_FATURAMENTO
  , CAST( COALESCE( SD2.D2_DESCON,0) AS DECIMAL(12,2))
      AS VL_DESCONTO_FATURAMENTO
  , CAST( COALESCE( SD2.D2_VALIRRF,0) AS DECIMAL(14,2))
      AS VL_IRF_FATURAMENTO
  , CAST( COALESCE( SD2.D2_VALINS,0) AS DECIMAL(14,2))
      AS VL_INSS_FATURAMENTO
	, CAST( COALESCE( SD2.D2_CUSTO1  * SD2.D2_QUANT,0) AS DECIMAL(14,2))
      AS VL_CUSTO_FATURAMENTO
  , CAST( COALESCE( SD2.D2_PESO   * SD2.D2_QUANT,0) AS DECIMAL(12,4))
      AS PESO_LIQUIDO
  , CAST( COALESCE( SB1.B1_PESBRU * SD2.D2_QUANT,0) AS DECIMAL(12,4))
      AS PESO_BRUTO
  , 1 
      AS QTD
  , CAST( COALESCE( SD2.D2_PRUNIT,0) AS DECIMAL(14,2))
      AS VL_UNITARIO
  , CAST( COALESCE( SD2.D2_SEGURO,0) AS DECIMAL(14,2))
      AS VL_SEGURO
  ,'01'
      AS INSTANCIA
  ,'P |01|SM2010|'+ COALESCE(RIGHT('00' + CAST( SF2.F2_MOEDA AS VARCHAR(2)),2),'|') 
      AS BK_MOEDA
  , COALESCE( SF2.F2_TXMOEDA,0)
      AS TAXA_MOEDA
  , '01'
        AS DOCUMENTO_CANCELADO
    , SL1.L1_IMEI
      AS IMEI_CELULAR
    ,SF2.F2_DESCONT 
        AS DESCONTO_NOTA


FROM SD2010 SD2
  INNER JOIN SF2010 SF2
    ON F2_FILIAL         = D2_FILIAL
    AND F2_CLIENTE    = D2_CLIENTE
    AND F2_LOJA       = D2_LOJA
    AND F2_DOC        = D2_DOC
    AND F2_SERIE      = D2_SERIE
    AND SF2.D_E_L_E_T_= ' '
  INNER JOIN SB1010 SB1
    ON B1_FILIAL = SUBSTRING(D2_FILIAL , 1 , 2)
    AND SB1.B1_COD    = SD2.D2_COD
    AND SB1.D_E_L_E_T_= ' '
  INNER JOIN SF4010 SF4
    ON F4_FILIAL = D2_FILIAL
    AND SF4.F4_CODIGO  = SD2.D2_TES
    AND SF4.D_E_L_E_T_ = ' '
  LEFT JOIN SA1010 SA1
    ON A1_FILIAL = SUBSTRING(D2_FILIAL , 1 , 2)
    AND SA1.A1_COD    = SF2.F2_CLIENTE
    AND SA1.A1_LOJA   = SF2.F2_LOJA
    AND SA1.D_E_L_E_T_= ' '
  LEFT JOIN SBM010 SBM
    ON SBM.BM_FILIAL = '    '
    AND SBM.BM_GRUPO       = SB1.B1_GRUPO
    AND SBM.D_E_L_E_T_ = ' '
  LEFT JOIN SA3010 SA3
    ON SA3.A3_FILIAL = SUBSTRING( SD2.D2_FILIAL , 1 , 2)
    AND SA3.A3_COD         = SF2.F2_VEND1
    AND SA3.D_E_L_E_T_ = ' '
  LEFT JOIN SX5010 CFOP
    ON CFOP.X5_FILIAL = '    '
    AND CFOP.X5_TABELA       = '13'
    AND CFOP.X5_CHAVE        = SD2.D2_CF
    AND CFOP.D_E_L_E_T_ = ' '
  LEFT JOIN SE4010 SE4
    ON SE4.E4_FILIAL = SUBSTRING( SD2.D2_FILIAL , 1 , 2)
    AND SE4.E4_CODIGO      = SF2.F2_COND
    AND SE4.D_E_L_E_T_ = ' '
  LEFT JOIN ACY010 ACY
    ON ACY.ACY_FILIAL = SUBSTRING( SD2.D2_FILIAL , 1 , 2)
    AND ACY.ACY_GRPVEN     = SA1.A1_GRPVEN
    AND ACY.D_E_L_E_T_ = ' '
  LEFT JOIN SAH010 SAH
    ON SAH.AH_FILIAL = SUBSTRING( SD2.D2_FILIAL , 1 , 2)
    AND SAH.AH_UNIMED      = SD2.D2_UM
    AND SAH.D_E_L_E_T_ = ' '
  LEFT JOIN SL1010 SL1 
    ON SL1.L1_FILIAL = SD2.D2_FILIAL
    AND SL1.L1_DOC = SD2.D2_DOC
    AND SL1.L1_SERIE = SD2.D2_SERIE
    AND SL1.D_E_L_E_T_ =''

WHERE
  F2_EMISSAO BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
  AND D2_TIPO NOT IN ('B', 'D' )