SELECT
    'P |01|01|' AS BK_EMPRESA
    , CASE WHEN L1_FILIAL IS NULL THEN 'P |01||' ELSE 'P |01|01' + CAST(L1_FILIAL AS CHAR(4)) END AS BK_FILIAL

    , L1_NUM AS NUMERO_ORCAMENTO
    , L1_DOC AS DOCUMENTO
    , L1_SERIE AS SERIE_DOCUMENTO
    , 'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL,' ') )+'|'+RTRIM(COALESCE(L1_CLIENTE,' ') ),' '),'|') AS BK_CLIENTE
    , 'P |01|SA3010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL,' ') )+'|'+RTRIM(COALESCE(L1_VEND,' ') ),' '),'|') AS BK_VENDEDOR
    , L1_EMISNF AS DATA
    , L1_HORA AS HORA_VENDA
    , L1_VLRTOT AS VALOR_TOTAL
    , L1_SITUA AS STATUS_VENDA
    , L1_NSUTEF AS NSU_TEF

    , L1_OPERADO AS BK_OPERADOR
    , L1_FORMPG AS FORMA_PAGAMENTO
    , L1_DINHEIR AS VALOR_DINHEIRO
    , L1_CARTAO AS VALOR_CARTAO
    , L1_VALES AS VALOR_VALES
    , L1_CREDITO AS VALOR_CARTAO_CREDITO
    , L1_VLRDEBI AS VALOR_CARTAO_DEBITO
    , L1_OUTROS AS VALOR_OUTROS
    , L1_PARCELA AS QTD_PARCELA

    , L1_ORCAMPS AS SERVICO_PRODUTO
    , L1_DTLIM AS DATA_LIMITE
    , L1_EMISSAO  AS DATA_DE_EMISSAO   



FROM SL1010 SL1

INNER JOIN SA1010 SA1 
                ON A1_COD = L1_CLIENTE 
                AND SA1.D_E_L_E_T_ = ' '

INNER JOIN SA3010 SA3 
                ON A3_COD = L1_VEND
                AND SA3.D_E_L_E_T_ = ' '

                

WHERE L1_EMISSAO BETWEEN 20221101 AND <<FINAL_DATE>>
    AND L1_EMISSAO <> 20221016
    AND L1_DTLIM <> 20221016
	AND L1_EMISNF <> 20221016
    AND SL1.D_E_L_E_T_ = ' '