SELECT 
    'P |01|01' 
        AS BK_EMPRESA
    ,CASE 
        WHEN D1_FILIAL IS NULL 
        THEN 'P |01||' 
        ELSE 'P |01|01'+ CAST(D1_FILIAL AS CHAR (4) ) 
        END 
        AS BK_FILIAL
    ,D1_DTDIGIT 
        AS DATA_DE_DEVOLUCAO
    ,'P |01|SX5010|'+COALESCE(NULLIF(RTRIM( COALESCE(CFOP.X5_FILIAL,' ') )+'|'+RTRIM( COALESCE(D1_CF,' ') ),' '),'|') 
        AS BK_CFOP
    ,D1_SERIE 
        AS SERIE_DOCUMENTO_CLIENTE
    ,D1_DOC 
        AS NUMERO_DOCUMENTO_CLIENTE
    ,F2_SERIE 
        AS SERIE_NOTA_FISCAL
    ,F2_DOC 
        AS NUMERO_DA_NOTA_FISCAL
    ,D1_ITEM 
        AS NUMERO_DO_ITEM_DO_DOCUMENTO
    ,D1_DOC + D1_SERIE 
        AS NUMERO_DO_ITEM_DA_NF
    ,D1_REMITO 
        AS NUMERO_DO_REMITO
    ,D1_SERIREM 
        AS SERIE_DO_REMITO
    ,D1_ITEMREM 
        AS ITEM_DO_REMITO
    ,'P |01|SF4010|'+COALESCE(NULLIF(RTRIM( COALESCE(F4_FILIAL,' ') )+'|'+RTRIM( COALESCE(D1_TES,' ') ),' '),'|') 
        AS BK_TES
    ,'P |01|SE4010|'+COALESCE(NULLIF(RTRIM( COALESCE(E4_FILIAL,' ') )+'|'+RTRIM( COALESCE(F2_COND,' ') ),' '),'|') 
        AS BK_CONDICAO_DE_PAGAMENTO
    ,'P |01|SB1010|'+COALESCE(NULLIF(RTRIM( COALESCE(B1_FILIAL,' ') )+'|'+RTRIM( COALESCE(D1_COD,' ') ),' '),'|') 
        AS BK_ITEM
    ,'P |01|SBM010|'+COALESCE(NULLIF(RTRIM( COALESCE(BM_FILIAL,' ') )+'|'+RTRIM( COALESCE(B1_GRUPO,' ') ),' '),'|') 
        AS BK_GRUPO_ESTOQUE
    ,'P |01|SA3010|'+COALESCE(NULLIF(RTRIM( COALESCE(A3_FILIAL,' ') )+'|'+RTRIM( COALESCE(F2_VEND1,' ') ),' '),'|') 
        AS BK_VENDEDOR
    ,'P |01|SA1010|'+COALESCE(NULLIF(RTRIM( COALESCE(A1_FILIAL,' ') )+'|'+RTRIM( COALESCE(D1_FORNECE,' ') )+RTRIM( COALESCE(D1_LOJA,' ') ),' '),'|') 
        AS BK_CLIENTE
    ,'P |01|SAH010|'+COALESCE(NULLIF(RTRIM( COALESCE(AH_FILIAL,' ') )+'|'+RTRIM( COALESCE(D1_UM,' ') ),' '),'|') 
        AS BK_UNIDADE_DE_MEDIDA
    ,CASE 
        WHEN SA1.A1_COD_MUN = ' ' 
        THEN 'P |01|CC2010|'+COALESCE(NULLIF(RTRIM( COALESCE(A1_EST,' ') ),' '),'|') 
        ELSE 'P |01|CC2010|'+COALESCE(NULLIF(RTRIM( COALESCE(A1_EST,' ') )+RTRIM( COALESCE(A1_COD_MUN,' ') ),' '),'|') 
        END 
        AS BK_REGIAO
    ,D1_QUANT 
        AS QTDE_DEVOLVIDA_ITEM
    ,D1_TOTAL+D1_VALIPI+D1_ICMSRET 
        AS VL_DEVOLUCAO_TOTAL
    ,D1_VALICM 
        AS VL_ICMS_DEVOLUCAO
    ,D1_VALIPI 
        AS VL_IPI_DEVOLUCAO
    ,(D1_TOTAL - (D1_VALICM + D1_VALIMP5 + D1_VALIMP6 + D1_VALDESC)) 
        AS VL_DEVOLUCAO_LIQUIDA
    ,D1_TOTAL - D1_VALDESC 
        AS VL_DEVOLUCAO_MERCADORIA
    ,D1_VALIMP6 
        AS VL_PIS_DEVOLUCAO
    ,D1_VALIMP5 
        AS VL_COFINS_DEVOLUCAO
    ,D1_ICMSRET 
        AS VL_ICMS_SUBST_DEVOLUCAO
    ,D1_VALDESC 
        AS VL_DESCONTO_DEVOLUCAO
    ,D1_VALINS 
        AS VL_INSS_DEVOLUCAO
    ,'01' 
        AS INSTANCIA
    ,'P |01|SM2010|'+COALESCE(RIGHT('00' + CAST(F2_MOEDA AS VARCHAR(2)),2),'|') 
        AS BK_MOEDA
    ,COALESCE(F2_TXMOEDA,0) 
        AS TAXA_MOEDA 

FROM SD1010 SD1 
    INNER JOIN SF2010 SF2 
        ON SF2.D_E_L_E_T_ = ' ' 
        AND F2_FILIAL = D1_FILIAL 
        AND F2_DOC = D1_NFORI 
        AND F2_SERIE = D1_SERIORI 
        AND F2_CLIENTE = D1_FORNECE 
        AND F2_LOJA = D1_LOJA 
    INNER JOIN SB1010 SB1 
        ON B1_FILIAL = SUBSTRING(F2_FILIAL , 1 , 2) 
        AND SB1.B1_COD = D1_COD 
        AND SB1.D_E_L_E_T_ = ' ' 
    LEFT JOIN SF4010 SF4 
        ON F4_FILIAL = D1_FILIAL 
        AND D1_TES = F4_CODIGO 
        ]AND SF4.D_E_L_E_T_ = ' ' 
    LEFT JOIN SE4010 SE4 
        ON E4_FILIAL = SUBSTRING(D1_FILIAL , 1 , 2) 
        AND E4_CODIGO = F2_COND 
        AND SE4.D_E_L_E_T_ = ' ' 
    LEFT JOIN SBM010 SBM 
        ON BM_FILIAL = '    ' 
        AND BM_GRUPO = B1_GRUPO 
        AND SBM.D_E_L_E_T_ = ' ' 
    LEFT JOIN SA3010 SA3 
        ON A3_FILIAL = SUBSTRING(F2_FILIAL , 1 , 2) 
        AND A3_COD = SF2.F2_VEND1 
        AND SA3.D_E_L_E_T_ = ' ' 
    LEFT JOIN SA1010 SA1 
        ON A1_FILIAL = SUBSTRING(F2_FILIAL , 1 , 2) 
        AND SA1.A1_COD = SF2.F2_CLIENTE 
        AND SA1.A1_LOJA = SF2.F2_LOJA 
        AND SA1.D_E_L_E_T_= ' ' 
    LEFT JOIN SAH010 SAH 
        ON AH_FILIAL = SUBSTRING(D1_FILIAL , 1 , 2) 
        AND AH_UNIMED = SD1.D1_UM 
        AND SAH.D_E_L_E_T_ = ' ' 
    LEFT JOIN SX5010 CFOP 
        ON X5_FILIAL = '    ' 
        AND X5_TABELA = '13' 
        AND X5_CHAVE = D1_CF 
        AND CFOP.D_E_L_E_T_ = ' ' 

WHERE  
    D1_DTDIGIT BETWEEN <<START_DATE>> AND <<FINAL_DATE>> 
    AND SD1.D_E_L_E_T_ = ' '